language: python
os:
  - linux
python:
  - "3.7"
  - "3.8"
before_install:
  - openssl aes-256-cbc -K $encrypted_cd5bf494279a_key -iv $encrypted_cd5bf494279a_iv -in tests/test_files.tar.enc -out tests/test_files.tar -d
  - tar xvf tests/test_files.tar
  - cd tests
  - ls
install:
  - pip install -r requirements.txt
  - pip install coverage
script: 
  - coverage run -m unittest tests.tests
after_success:
  - bash <(curl -s https://codecov.io/bash)